# The next line is the forcing function for the Firebase pod. The Firebase
# version's subspecs should depend on the component versions in their
# corresponding podspec's.
pod 'Firebase/Core', '4.8.1'

use_frameworks!
platform :ios, '8.0'

target 'Firestore_Example' do
  pod 'FirebaseAuth', :path => '../../'
  pod 'FirebaseCore', :path => '../../'
  pod 'FirebaseFirestore', :path => '../../'
  pod 'gRPC', :podspec => 'gRPC.podspec'
  pod 'gRPC-C++', :podspec => 'gRPC-C++.podspec'
  pod 'gRPC-Core', :podspec => 'gRPC-Core.podspec'
  pod 'gRPC-ProtoRPC', :podspec => 'gRPC-ProtoRPC.podspec'
  pod 'gRPC-RxLibrary', :podspec => 'gRPC-RxLibrary.podspec'

  target 'Firestore_Tests' do
    inherit! :search_paths

    pod 'FirebaseCore', :path => '../../'
    pod 'leveldb-library'

    pod 'OCMock'
    pod 'GoogleTest', :podspec => 'Tests/GoogleTest/GoogleTest.podspec'
  end

  target 'Firestore_IntegrationTests' do
    inherit! :search_paths

    pod 'FirebaseCore', :path => '../../'

    pod 'OCMock'
  end
end

target 'SwiftBuildTest' do
  pod 'FirebaseFirestore', :path => '../../'
end
